/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AlphaAgentRegistry__factory } from "./AlphaAgentRegistry__factory";
export { AlphaPaymentHub__factory } from "./AlphaPaymentHub__factory";
